# Generated by Django 5.0 on 2024-01-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('fullname', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=150)),
                ('sub', models.CharField(max_length=150)),
                ('ex_location', models.CharField(max_length=150)),
                ('ex_class', models.CharField(max_length=150)),
                ('living_place', models.CharField(max_length=150)),
                ('ex_salary', models.IntegerField()),
            ],
        ),
    ]
