# Generated by Django 5.0 on 2024-01-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0002_teachermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tution/images/'),
        ),
    ]
