# Generated by Django 5.0 on 2024-01-15 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tution', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appaly_status', models.CharField(choices=[('Pending', 'Pending'), ('Selected', 'Selected'), ('Completed', 'Completed')], default='Pending', max_length=30)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('cancel', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.applicantmodel')),
                ('tution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tution.tutionmodel')),
            ],
        ),
    ]
